### PR TITLE
chore: setup workspace-hack config so hakari works

### PR DESCRIPTION
**Pull request by hiltontj**
Added the `.config/hakari.toml` file from IOx, and then ran `cargo hakari generate`. Having this in working order will be necessary for setting up CI, see #5

### CODE REVIEW

**Review by mgattozzi — COMMENTED** [review]
I remember that when I split out core I had some issues with the cargo workspace in the OSS repo. I think it was just that we couldn't use the hack here and in OSS. Do you mind testing the OSS repo with these changes included before I approve it?

**Comment by hiltontj** [comment]
> Do you mind testing the OSS repo with these changes included before I approve it?

Good call, I will open a test PR in `influxdb`

**Comment by hiltontj** [comment]
@mgattozzi - I opened https://github.com/influxdata/influxdb/pull/24937 to run CI using this branch and looks ✅

**Review by mgattozzi — APPROVED** [review]
Great let's get it in!

**Pull request merged**
